#!/usr/bin/env bash
# Convert a QMK keymap.json & layout.h to keymap-drawer yaml
test -z "$QMK_HOME" && echo "Must set QMK_HOME to root qmk_firmware dir" && exit 1 || true
test -z "$(which qmk)" && echo "Must have qmk_cli installed" && exit 2 || true
test -z "$(which pcpp)" && echo "Must have pcpp cli installed" && exit 3 || true
test "$#" != 2 && echo "Usage: ./json2yaml qmk-keymap.json layout.h" && exit 4 || true
keymap_yaml='/tmp/keymap.yaml'
keymap_json="$1"
layout_h="$2"

# (1) Convert keymap.json (containing only layer name macros) to keymap.c
# (2) Expand layer macros (define KEYMAP_DISPLAY so that aliases for shortcuts are not expanded)
# (3) Convert keymap.c to QMK keymap.json
# (4) Parse fully expanded QMK keymap.json into yaml using keymap-drawer
qmk json2c "$keymap_json" -o /tmp/keymap-json.c 2> /dev/null 
pcpp -D QMK_KEYBOARD_H="" -D KEYMAP_DISPLAY $layout_h /tmp/keymap-json.c > /tmp/keymap.c
qmk c2json -kb "$(jq -r '.keyboard' $keymap_json)" -km default /tmp/keymap.c > /tmp/keymap.json 
keymap parse -q /tmp/keymap.json > "$keymap_yaml"

# Handle held keys
perl -i -pe "s|\bHELD\b|{type: held}|g" "$keymap_yaml"

# Restore layer names using layer macro names in keymap.json 
i=0
layers=$(jq -cr ".layers[][0]" $keymap_json | sed 's|\s*\_||g')
for name in $layers; do
    perl -i -pe "s|\bL$i\b|$name|g" "$keymap_yaml"  # yaml layer names
    perl -i -pe "s|\($i\)|($name)|g" "$keymap_yaml" # keycode refs (eg: MO, OSL, etc)
    perl -i -pe "s|t: '$i', h: sticky|t: '$name', h: sticky|g" "$keymap_yaml" # OSL
    let i=${i}+1
done

# TODO: remove after https://github.com/caksoylar/keymap-drawer/pull/4 is released
# Replace one-shot keycodes as tap codes with stick hold label
oneshots=$(grep -Eo 'OS[ML]\(\w+)' "$keymap_yaml" | sort | uniq)
for key in $oneshots; do
    keycode=$(echo $key | tr -d "()" | sed 's|OS[ML]||g; s|^MOD_||g')
    replacement="{t: $keycode, h: sticky}"
    sed -i.bak "s|$key|$replacement|g" "$keymap_yaml"
done

# TODO: remove after https://github.com/caksoylar/keymap-drawer/pull/5 is released
# Replace underscores in labels from defines so it wraps
upper_snake_labels=$(grep -oE '\w+(_\w+)+' "$keymap_yaml" | sort | uniq | grep -vE '[a-z]')
for label in $upper_snake_labels; do
    replacement=$(echo $label | sed 's|\_| |g')
    sed -i.bak "s|$label|$replacement|g" "$keymap_yaml"
done

cat "$keymap_yaml"
