name: Render keymap image

on:
  workflow_call:
    inputs:
      output_type:
        description: "Output format (kle | kd)"
        default: "kle"
        required: true
        type: string
      keymap_type:
        description: "Type of keymap file (qmk | zmk | nf)"
        default: "qmk"
        required: true
        type: string
      keymap_path:
        description: "Path to the keymap (.h layout file)"
        default: "../layout.h"
        required: true
        type: string
      keymap_json_path:
        description: "Path to the keymap json"
        default: ""
        required: false
        type: string
      config_path:
        description: "Path to the config (legends)"
        default: None
        required: false
        type: string

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Checkout keymap-display
      uses: actions/checkout@v3
      with: 
        repository: jbarr21/keymap-display
        path: keymap-display 
    - name: Checkout qmk-firmware
      uses: actions/checkout@v3
      with: 
        repository: qmk/qmk_firmware
        path: qmk_firmware
    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '88.0.4324.96'
    - name: Launch browser
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pushd $GITHUB_WORKSPACE/keymap-display
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        popd
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
    - name: Generate & download the image
      run: |
        export QMK_HOME="$GITHUB_WORKSPACE/qmk_firmware"
        pushd $GITHUB_WORKSPACE/keymap-display
        pipenv run python keymap_display/keymap-display.py -l -s -i ${{ inputs.keymap_type }} -o ${{ inputs.output_type }} -c ${{ inputs.config_path }} -j ../${{ inputs.keymap_json_path }} ../${{ inputs.keymap_path }} || true
        find "$GITHUB_WORKSPACE" -name "keymap.svg"
        mv $GITHUB_WORKSPACE/keymap-display/keymap.svg $GITHUB_WORKSPACE || true
        find "$GITHUB_WORKSPACE" -name "*.png"
        mv $GITHUB_WORKSPACE/keymap-display/keyboard-layout.png $GITHUB_WORKSPACE || true
        popd
    - name: Commit updated image
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Skip CI] Automated keymap render"
        file_pattern: "*.svg *.png"